return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
		preset = "modern",
		delay = 300,
		plugins = {
			marks = true,
			registers = true,
			spelling = { enabled = true, suggestions = 20 },
		},
		spec = {
			{ "<leader>a", group = "AI: Sidekick (Claude/Codex/OpenCode/Copilot CLI)" },
			{ "<leader>b", group = "Buffers" },
			{ "<leader>c", group = "Chat (CopilotChat)" },
			{ "<leader>d", group = "Debug (DAP)" },
			{ "<leader>f", group = "Find / Files" },
			{ "<leader>g", group = "Git" },
			{ "<leader>h", group = "Hunks (Git)" },
			{ "<leader>j", group = "Join / Split (treesj)" },
			{ "<leader>l", group = "LSP / Lint / Format" },
			{ "<leader>m", group = "Marks (Harpoon)" },
			{ "<leader>n", group = "AI Companion (CodeCompanion) / Noice" },
			{ "<leader>o", group = "Overseer (run scripts)" },
			{ "<leader>p", group = "Package info" },
			{ "<leader>r", group = "Refactor / Rename" },
			{ "<leader>s", group = "Search / Sessions / Spectre" },
			{ "<leader>T", group = "Tests (Jest)" },
			{ "<leader>u", group = "UI toggles (Outline, Colors, Context)" },
			{ "<leader>x", group = "Trouble / Diagnostics" },
		},
	},
}
